$rosewater = rgb(f3e8ff)
$rosewaterAlpha = f3e8ff

$flamingo = rgb(e9d5ff)
$flamingoAlpha = e9d5ff

$pink = rgb(d8b4fe)
$pinkAlpha = d8b4fe

$mauve = rgb(c084fc)
$mauveAlpha = c084fc

$red = rgb(a855f7)
$redAlpha = a855f7

$maroon = rgb(9333ea)
$maroonAlpha = 9333ea

$peach = rgb(7e22ce)
$peachAlpha = 7e22ce

$yellow = rgb(6b21a8)
$yellowAlpha = 6b21a8

$green = rgb(581c87)
$greenAlpha = 581c87

$teal = rgb(4c1d95)
$tealAlpha = 4c1d95

$sky = rgb(4338ca)
$skyAlpha = 4338ca

$sapphire = rgb(3730a3)
$sapphireAlpha = 3730a3

$blue = rgb(312e81)
$blueAlpha = 312e81

$lavender = rgb(2e1065)
$lavenderAlpha = 2e1065

$text = rgb(f5f3ff)
$textAlpha = f5f3ff

$subtext1 = rgb(e9d5ff)
$subtext1Alpha = e9d5ff

$subtext0 = rgb(d8b4fe)
$subtext0Alpha = d8b4fe

$overlay2 = rgb(c4b5fd)
$overlay2Alpha = c4b5fd

$overlay1 = rgb(a78bfa)
$overlay1Alpha = a78bfa

$overlay0 = rgb(8b5cf6)
$overlay0Alpha = 8b5cf6

$surface2 = rgb(7c3aed)
$surface2Alpha = 7c3aed

$surface1 = rgb(6d28d9)
$surface1Alpha = 6d28d9

$surface0 = rgb(5b21b6)
$surface0Alpha = 5b21b6

$base = rgb(4c1d95)
$baseAlpha = 4c1d95

$mantle = rgb(3b0764)
$mantleAlpha = 3b0764

$crust = rgb(2e1065)
$crustAlpha = 2e1065
