{pkgs,inputs}: with pkgs; [
    hyprpolkitagent
        mesa
    nwg-look
    waybar
    killall
    gammastep
    dunst
    tofi
    cliphist
    wl-clipboard
    swww
    hyprpicker
    hyprlock
    wlogout
    grimblast
    hypridle
    pamixer
    pipewire
    pwvucontrol
    playerctl
    brightnessctl
    greetd.tuigreet
]++[
 inputs.rose-pine-hyprcursor.packages.${pkgs.system}.default
  ]
