{pkgs,inputs}: with pkgs; [
  hyprpolkitagent
  mesa
  nwg-look
  waybar
  #ppsspp
  killall
  gammastep
  dunst
  tofi
  wl-clipboard
  swww
  hyprlock
  wlogout
  grimblast
  hypridle
  pamixer
  hyprpicker
  pwvucontrol
  playerctl
  brightnessctl
  tuigreet
]++[
  inputs.rose-pine-hyprcursor.packages.${pkgs.system}.default
  inputs.astm.packages.${system}.default
  inputs.llama-cpp.packages.${system}.vulkan
]
