{pkgs}: with pkgs; [
        python314
        alacritty
        neovim
        pkg-config
        libevdev
        ripgrep
        fd
        git
        android-studio
        android-tools
        watchman
        web-ext
        jdk24
        kotlin
        gradle_8
        gcc
        gnumake
        raylib
]
