{pkgs}: with pkgs; [
        libva
        libva-utils
        intel-media-driver
        vdpauinfo
        libvdpau-va-gl
        intel-gpu-tools
        intel-ocl
        intel-compute-runtime-legacy1
        vulkan-tools
        gnome.gvfs 
        libmtp
        jmtpfs
        pciutils
        htop
        nautilus
        emote
        pcsx2
        neofetch
        steam-run
        spotify
        unzip
        mpv
        libreoffice-qt6-fresh
        postman
        obs-studio
        godot_4
]
